### ISSUE TITLE
Mutual Data Availability in Pan-Cancer Dataset

### ISSUE THREAD

**Issue by cannin** [sanderlab/tumorcomparer#12]
How many genes are available across all data types and sources (TCGA/CCLP)? What about within individual data types?

**Comment by hakobyansiras** [comment]
There are 9099 mutual genes across all data types. 
For individual data types the number of mutual genes are:
Mutation: 14829
CNA: 16264
Expression: 14429

**Comment by cannin** [comment]
thanks
