### ISSUE TITLE
Testing Geneset Specific Function

### ISSUE THREAD

**Issue by cannin** [sanderlab/tumorcomparer#13]
@hakobyansiras 

Go here:
https://www.cell.com/cell-reports-methods/fulltext/S2667-2375(21)00084-9

Look at figure 4

See if your function can reproduce Figure 4

The tumorcomparer package folder data has tcga_pancan_pathway_genes.rda with a list of vectors that has the gene symbols for RTKRAS and WNT.

**Comment by hakobyansiras** [comment]
![image](https://user-images.githubusercontent.com/50982874/125640177-d4504d50-321c-472d-bed6-a8bd6c8387bd.png)
![image](https://user-images.githubusercontent.com/50982874/125640363-642571ff-ed15-4981-b890-247dc917098d.png)
![image](https://user-images.githubusercontent.com/50982874/125640397-a593992d-7bd5-4775-b757-a00cc64d91af.png)
![image](https://user-images.githubusercontent.com/50982874/125640437-b466d574-615e-44ff-96d8-7cb98c6bbb92.png)

**Comment by cannin** [comment]
@Optimistix @hakobyansiras how do these compare with the plots in the publication?

**Comment by cannin** [comment]
An initial function has been added
