### ISSUE TITLE
Geneset filtering issue

### ISSUE THREAD

**Issue by hakobyansiras** [sanderlab/tumorcomparer#15]
This table presents the number of detected genes for each geneset in all data types. There are two issues to be addressed
1. The minimum possible number of genes for comparison is 4, the algorithm gives an error when less than 4 gene data is provided
2. Number of filtered genes for specific geneset can be different across data types

![image](https://user-images.githubusercontent.com/50982874/126328466-42e755d6-66c0-4ff6-b7f7-0dae24d1fca8.png)

**Comment by cannin** [comment]
@hakobyansiras let's set the limit to 5 genes. You will probably need to do this in the generalized function you created.

**Comment by cannin** [comment]
@hakobyansiras there needs to be error checking code that considers situations where all values are 0. Also, in the case where one dataset has all zeros, a user may want to remove the dataset from consideration. This should not be the default behavior. An error should be triggered in this case and a user should be able to override it with a flag: remove_errored_dataset_comparisons=FALSE

**Comment by cannin** [comment]
@hakobyansiras make sure there are unit tests with data for these error cases

**Comment by hakobyansiras** [comment]
What we are going to do with precomputed comparisons? 
Do I need to keep the cases where one data type is missing(because of the zeros)? If yes, then it should be reported that one or another data type is missing in this comparison because there are no available values for specified geneset in the certain data type(s).

**Comment by cannin** [comment]
A test has been added for the case with fewer than 5 genes
