### ISSUE TITLE
Datatypes with zero values in precomputed comparisons

### ISSUE THREAD

**Issue by hakobyansiras** [sanderlab/tumorcomparer#16]
What we are going to do with precomputed comparisons? 
Do I need to keep the cases where one data type is missing(because of the zeros)? If yes, then it should be reported that one or another data type is missing in this comparison because there are no available values for specified geneset in the certain data type(s).

**Comment by cannin** [comment]
@hakobyansiras record the datatypes used in the comparison with a new list item here: https://github.com/sanderlab/tumorcomparer/blob/8027da9bfca5323c21107c63974cbee3d916bae1/R/run_comparison_config_list.R#L65 

Then in the Shiny app we can append the data used (e.g., "BRCA, Pathway: RTK, Data: mut, exp")
