### ISSUE TITLE
Igrah layout integration into cyjShiny netowrk

### ISSUE THREAD

**Issue by hakobyansiras** [sanderlab/tumorcomparer#25]
```
dist_mat_melted <- reshape2::melt(`is.na<-`(dist_mat, upper.tri(dist_mat, diag = T)), na.rm = TRUE)

g <- graph::ftM2graphNEL(as.matrix(dist_mat_melted[which(dist_mat_melted$value > min_weight),1:2]), edgemode = "directed")
  
  graph::nodeDataDefaults(g, attr = "label") <- "NA"
  graph::nodeDataDefaults(g, attr = "color") <- "NA"
  graph::nodeDataDefaults(g, attr = "xPos") <- 0
  graph::nodeDataDefaults(g, attr = "yPos") <- 0
  
  graph::nodeData(g, attr = "label") <- graph::nodes(g)
  graph::nodeData(g, graph::nodes(g)[grepl("TCGA", graph::nodes(g))], attr = "color") <- "#99ccff"
  graph::nodeData(g, graph::nodes(g)[!grepl("TCGA", graph::nodes(g))], attr = "color") <- "#49d849"
  graph::nodeData(g, attr = "xPos") <- igraph::layout_nicely(igraph::graph_from_graphnel(g))[,1]
  graph::nodeData(g, attr = "yPos") <- igraph::layout_nicely(igraph::graph_from_graphnel(g))[,2]
  
  graph::edgeDataDefaults(g, attr = "edgeType") <- "pp"
  graph::edgeDataDefaults(g, attr = "dist") <- 0
  
  graph::edgeData(g, from = as.character(dist_mat_melted[which(dist_mat_melted$value > min_weight),1]), 
                  to = as.character(dist_mat_melted[which(dist_mat_melted$value > min_weight),2]), 
                  attr = "dist") <- round(dist_mat_melted[which(dist_mat_melted$value > min_weight),3], digits = 2)
  
  return(cyjShiny::graphNELtoJSON(g))
```

I am building cyjShiny json graph with this code. However, can't figure out what to change in the future code to make coordinates work.

**Comment by cannin** [comment]
@hakobyansiras what is "future code"?

**Comment by hakobyansiras** [comment]
I could not reproduce the layout in cyjShiny based on the coordinates. It appeared that it was a scaling issue, I multiplied coordinates by 100 and it kind of worked. However, when the similarity threshold is low then a high number of nodes causing a scaling issue again.

**Comment by cannin** [comment]
@hakobyansiras post screenshot

**Comment by hakobyansiras** [comment]
Switched to igraph layout in cyjShiny network(there are coordinates scaling issues with big networks(need to find out how network margins are set). I will try to improve layout). Putting some screenshots.
Small network
![image](https://user-images.githubusercontent.com/50982874/129445595-4c9ce4da-5750-4533-9d3d-ad645b72aa8a.png)
Big network
![image](https://user-images.githubusercontent.com/50982874/129445611-36925e1e-0566-4329-9b97-b9e97fa6e2aa.png)

**Comment by cannin** [comment]
Figure out a number that works for 0.5 similarity on the combined score then see if it is reasonable for higher values. We may not show anything smaller than 0.5.

**Comment by hakobyansiras** [comment]
It is taking 15 seconds to build a network for 0.5 value. The resulting graph has 140 nodes and 4256 edges. I think it is useless to look at the graph with 4256 edges. 
Maybe it is a good idea to make a threshold for the maximum number of edges(let's say if the number of edges exceeds 500 keep only the top 500.)

**Comment by hakobyansiras** [comment]
Visnetwork will manage this much faster and easier. However, there is no much useful visual information from this network.
![image](https://user-images.githubusercontent.com/50982874/129446519-4f65c601-3f27-482e-9744-850b2ea41cfe.png)
