### ISSUE TITLE
GitHub actions Error for windows check

### ISSUE THREAD

**Issue by hakobyansiras** [sanderlab/tumorcomparer#26]
Github actions throw an Error for windows check, the rest of OSs are passing the tests. 
Can't figure out what is wrong
look at the error here: https://github.com/hakobyansiras/tumorcomparer/runs/3328749610#step:9:446

**Comment by cannin** [comment]
Change expect_identical() to expect_equal(): https://testthat.r-lib.org/reference/equality-expectations.html

**Comment by hakobyansiras** [comment]
Thank you, all tests are now successfully finished.
