### ISSUE TITLE
What to fix in specified places?

### ISSUE THREAD

**Issue by hakobyansiras** [sanderlab/tumorcomparer#27]
What do I need to fix in these parts of the code? (there were FIXME marks)
https://github.com/hakobyansiras/tumorcomparer/blob/e58440b0f5e04642cfe30ac24387d4c025162a4e/R/make_balloon_plot_data_from_comparison_result.R#L75
https://github.com/hakobyansiras/tumorcomparer/blob/e58440b0f5e04642cfe30ac24387d4c025162a4e/inst/shinyApp/global.R#L36

**Comment by cannin** [comment]
1. Remove the FIXME comment in the plot R file
2. Write: mtc_dataset$Categorization <- mtc_dataset$Categorization for the global.R (Remove comment and FIXME)

**Comment by hakobyansiras** [comment]
Done
