### ISSUE TITLE
Minor Edits to Shiny App

### ISSUE THREAD

**Issue by cannin** [sanderlab/tumorcomparer#34]
* [x] Put a newline "\n" before "Data" for the Results Plot in pre-computed analysis (NOTE: only leave it if it does not overlap with the plot below); post screenshot here if it overlaps plot
* [x] Comment out VisNetwork UI and Server Code in Shiny
* [x] Capitalize each word for "Select geneset" -> "Select Geneset" and Similarity threshold
* [x] Leave only the Combined distance matrix option

**Comment by hakobyansiras** [comment]
1.
![image](https://user-images.githubusercontent.com/50982874/130281819-e67287eb-483d-4d28-889e-4772bf1db1d3.png)
2. There is no VisNetwork script in the code (it is only in shiny server for demonstration)
3. Done
4. Done
