### ISSUE TITLE
Fix no visible binding for global variable issue

### ISSUE THREAD

**Issue by cannin** [sanderlab/tumorcomparer#40]
@hakobyansiras Fix no visible binding for global variable issue in the file: 
https://github.com/sanderlab/tumorcomparer/blob/master/R/tcga_geneset_comparison.R

using VAR[, COLUMN, with = FALSE] notation

See https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/

**Comment by hakobyansiras** [comment]
Done
