### ISSUE TITLE
Package build warnings

### ISSUE THREAD

**Issue by hakobyansiras** [sanderlab/tumorcomparer#5]
1st warning
Warning: Maintainer: ‘Rileen Sinha <rileen@gmail.com>, Augustin Luna <aluna@jimmy.harvard.edu>’
The maintainer field is invalid or specifies more than one person

2nd warning
Warning: Undocumented arguments in documentation object 'plot_balloon_plot'
  ‘xlab’

link: https://github.com/hakobyansiras/tumorcomparer/runs/2810749256?check_suite_focus=true

**Comment by cannin** [comment]
## First Warning 
1st warning change to: 

Authors@R: c(
   person("Hadley", "Wickham", email = "hadley@rstudio.com", role = "cre"),
   person("Winston", "Chang", email = "winston@rstudio.com", role = "at"))

See: https://r-pkgs.org/description.html

## Second Warning
Add

`
#' @param xlab a string to be the x axis label for the plot 
`
After param title

**Comment by hakobyansiras** [comment]
**Package build notes**

> checking installed package size ... NOTE
    installed size is 41.1Mb
    sub-directories of 1Mb or more:
      extdata      26.5Mb
      shinyApp      5.4Mb
      test_output   8.0Mb

> checking DESCRIPTION meta-information ... NOTE
  Malformed Description field: should contain one or more complete sentences.

> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘LICENSE.md’

> checking R code for possible problems ... NOTE
  plot_joyplot: no visible binding for global variable ‘Var1’
  plot_joyplot: no visible binding for global variable ‘value’
  Undefined global functions or variables:
    Var1 value
